### ISSUE TITLE
(esp32) Example "streams-i2s-webserver wav.ino" not working in latest release  (0.6)

### ISSUE THREAD

**Issue by vernonet** [pschatzmann/arduino-audio-tools#23]
Get error "Guru Meditation Error: Core  1 panic'ed (LoadProhibited)". Perhaps a problem with a pointer "encoded_stream".
But the example works well in release arduino-audio-tools-0.4

**Comment by Chemita23** [comment]
config.sample_rate = 22050;

**Comment by xandyxor** [comment]
All the ways to leave a message don't fix the crazy noise
Only setting bits_per_sample to 32 can solve the noise

total heap size = 402496
available heap = 376280
lowest level of free heap since boot = 369872
largest block of heap that can be allocated at once = 126788
total Psram size = 0
available Psram = 0
lowest level of free Psram since boot = 0
largest block of Psram that can be allocated at once = 0
get Chip Revision = 1
getCpuFreqMHz = 240
get Cycle Count = 1685575244
get SdkVersion = v3.3.5-1-g85c43024c
