### ISSUE TITLE
multi peers is possible in communication-espnow-send ?

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#590]
i want to send data to multiple esp's  using esp now . is this possible ? and how ?

**Comment by pschatzmann** [comment]
Strange question: I assume that you want to use my ESPNowStream class. Did you look at the API of https://pschatzmann.github.io/arduino-audio-tools/html/classaudio__tools_1_1_e_s_p_now_stream.html
In ESPNow you need to register the peer(s), so instead of adding just one add more then one!

Please do not open and issue becuase this is clearly not one.  You can use a discussion instead, but only after first checking the documentation!
